### ISSUE TITLE
Server stacktrace after login (release/v5.0.0)

### ISSUE THREAD

**Issue by rubensworks** [solid/node-solid-server#1000]
After logging in, the server prints the following stacktrace:

```
(node:29945) UnhandledPromiseRejectionWarning: Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (/Users/rtaelman/Documents/UGent/nosync/node-solid-server/node_modules/express/lib/response.js:767:10)
    at addLink (/Users/rtaelman/Documents/UGent/nosync/node-solid-server/lib/header.js:22:9)
    at linksHandler (/Users/rtaelman/Documents/UGent/nosync/node-solid-server/lib/header.js:77:3)
    at <anonymous>
```

**Comment by rubensworks** [comment]
Fixed in #1013
