### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by mikael1234** [solid/node-solid-server#1128]
OS: Ubuntu 16.04.5 LTS, node v11.10.1

Installing Solid server with 

> sudo npm install -g solid-server

results following errors:

npm WARN deprecated nodemailer@3.1.8: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated text-encoding@0.6.4: no longer maintained
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
/usr/bin/solid -> /usr/lib/node_modules/solid-server/bin/solid

> spawn-sync@1.0.15 postinstall /usr/lib/node_modules/solid-server/node_modules/spawn-sync
> node postinstall

internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/solid-server/node_modules/spawn-sync/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at internal/main/run_main_module.js:21:11
npm WARN babel-preset-metalab@1.0.0 requires a peer of babel-core@^6.24.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-literal-to-ast@1.0.0 requires a peer of babel-core@>=6.0.20 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!

**Comment by kjetilk** [comment]
Thanks a lot!

What I have found about this so far is that `spawn-sync` seems obsoleted, and could be removed. Problem seems that is required by ancient versions of `inquirer`, which is eventually depended on by our old `standard`, and upgrading `standard` would mean relatively large changes to the rest of the code, so I am at this point not sure what to do about it. The version management here seems to be highly inflexible though, but that's not something we can fix.

**Comment by mikael1234** [comment]
Until permanent solution is found, can you think of any temp fix to get server running for test purposes?

**Comment by kjetilk** [comment]
I must admit that I'm not too familiar with `npm` itself, so I don't know. Lets hope for someone else to step up and suggest something, either here or in the forums. I'll write a note in the forums so that people understand it has not been resolved.

**Comment by angelo-v** [comment]
I cannot reproduce it.
```
 docker run node:11-alpine npm install -g solid-server
```
works without errors.

Might be specific to Ubuntu 16.04, which has a binary called `nodejs`, but not `node`:
https://github.com/ForbesLindesay/spawn-sync/issues/42
