### ISSUE TITLE
Server error after consent dialog

### ISSUE THREAD

**Issue by kjetilk** [solid/node-solid-server#1206]
When trying out https://zenomt.zenomt.com/testauth/check.html using my own https://solid.kjernsmo.net/ as IDP, I'm seeing an error in my logs:
```
(node:20447) UnhandledPromiseRejectionWarning: TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at ConsentRequest.getAppOrigin (/usr/lib/node_modules/solid-server/lib/requests/consent-request.js:137:24)
    at get (/usr/lib/node_modules/solid-server/lib/requests/consent-request.js:69:31)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/solid-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/solid-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/lib/node_modules/solid-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/solid-server/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/solid-server/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/lib/node_modules/solid-server/node_modules/express/lib/router/index.js:335:12)
```
This happens just after clicking through the consent dialog

**Comment by kjetilk** [comment]
Latest attempt from an incognito window:

```

  solid:authentication Logging in via username + password +12s
  solid:authentication Attempting to login user: solid.kjernsmo.net/profile/card#me +0ms
  solid:authentication User found, password matches +126ms
  solid:authentication Initializing user session with webId:  https://solid.kjernsmo.net/profile/card#me +0ms
  solid:authentication Login successful, redirecting to  https://solid.kjernsmo.net/consent?response_type=code&display=&scope=openid%20webid&client_id=7345f63085f79770411e01d8ad44b7b4&redirect_uri=https%3A%2F%2Fzenomt.zenomt.com%2Fauth%2Fcode&state=YccQp7wG-WbYMkMOqVe5hsfTrxixrLLI89Gu1jx7&nonce=24WXMVQzKQ6TL-8e&request= +0ms

  solid:authentication User is already authenticated as https://solid.kjernsmo.net/profile/card#me +15s
(node:20447) UnhandledPromiseRejectionWarning: TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at ConsentRequest.getAppOrigin (/usr/lib/node_modules/solid-server/lib/requests/consent-request.js:137:24)
    at get (/usr/lib/node_modules/solid-server/lib/requests/consent-request.js:69:31)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/solid-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/solid-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/lib/node_modules/solid-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/solid-server/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/solid-server/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/lib/node_modules/solid-server/node_modules/express/lib/router/index.js:335:12)
(node:20447) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 137)
```

**Comment by kjetilk** [comment]
BTW, ![a screenshot](file:///mnt/robin/kjetil/scratch/Screenshot_20190529_013554.png)

**Comment by kjetilk** [comment]
BTW, I have a screenshot too, showing the consent dialog as I see it. There are no checkboxes there:
http://dev.kjernsmo.net/tmp/Screenshot_20190529_013554.png

**Comment by michielbdejong** [comment]
@kjetilk can you debug this and try to fix it?

**Comment by michielbdejong** [comment]
if not, i can have a look.

**Comment by kjetilk** [comment]
I'm not sure it is worth fixing, unless someone else encounters it as well. I'm thinking that I/we will migrate towards to new server soon anyway, and if I'm the only one affected by it, then I'm inclined to just wait.

**Comment by michielbdejong** [comment]
ok, let's wait to see if anyone can reproduce this.

**Comment by jaxoncreed** [comment]
Has anyone been able to replicate this in the most recent versions of NSS? Can this be closed out?

**Comment by kjetilk** [comment]
Yeah, I couldn't reproduce this on 5.1.5 either.
