### ISSUE TITLE
Permission failure on favicon.lock 

### ISSUE THREAD

**Issue by timbl** [solid/node-solid-server#1214]
- Why is favicon.ico being locked anyway, as it doesn't get written
- Why is favicon involved in a mkdir call - maybe a lockfile is a directory

 ```
solid:get GET -- Error: undefined EACCES: permission denied, mkdir '/Library/WebServer/Documents/favicon.ico.lock' +15m
  solid:server Error page because of: { [Error: EACCES: permission denied, mkdir '/Library/WebServer/Documents/favicon.ico.lock']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/Library/WebServer/Documents/favicon.ico.lock'
```

**Comment by timbl** [comment]
More stack trace suggests a problem with releaseLock:
```
(node:75782) UnhandledPromiseRejectionWarning: TypeError: releaseLock is not a function
    at Promise (/devel/github.com/solid/node-solid-server/lib/lock.js:25:13)
(node:75782) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 36)
  solid:get GET -- Error: undefined EACCES: permission denied, mkdir '/Library/WebServer/Documents/favicon.ico.lock' +2m
  solid:server Error page because of: { [Error: EACCES: permission denied, mkdir '/Library/WebServer/Documents/favicon.ico.lock']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/Library/WebServer/Documents/favicon.ico.lock' } +0ms
(node:75782) UnhandledPromiseRejectionWarning: TypeError: releaseLock is not a function
    at Promise (/devel/github.com/solid/node-solid-server/lib/lock.js:25:13)
(node:75782) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 37)
```

**Comment by jaxoncreed** [comment]
Hmm this is weird. Thanks for pointing this out. We don't want to have these cluttering up the logs. I'm not sure when I'll have time to get to this but I'll pick it up when I can.
