### ISSUE TITLE
systemd service fails

### ISSUE THREAD

**Issue by ewingson** [solid/node-solid-server#1229]
have nss running on port 443. manual start works fine. systemd service fails with `result start limit`. have omitted the restart on failure to get more debug info. will include solid.service and the systemctl -l status solid.service                                                 

/lib/systemd/system/solid.service
```
[Unit]
Description=solid - social linked data
Documentation=https://solid.inrupt.com/docs/
After=network.target

[Service]
Type=simple
User=solid
WorkingDirectory=/var/www/solidweb.org
ExecStart=/usr/bin/solid start

[Install]
WantedBy=multi-user.target
```

systemctl -l status solid.service
```
● solid.service - solid - social linked data
   Loaded: loaded (/lib/systemd/system/solid.service; enabled)
   Active: failed (Result: exit-code) since Sa 2019-06-15 11:10:25 CEST; 1min 15s ago
     Docs: https://solid.inrupt.com/docs/
  Process: 19872 ExecStart=/usr/bin/solid start (code=exited, status=1/FAILURE)
 Main PID: 19872 (code=exited, status=1/FAILURE)

Jun 15 11:10:25 lvps83-169-46-66.dedicated.hosteurope.de solid[19872]: at Server.setupListenHandle [as _listen2] (net.js:1343:19)
Jun 15 11:10:25 lvps83-169-46-66.dedicated.hosteurope.de solid[19872]: at listenInCluster (net.js:1401:12)
Jun 15 11:10:25 lvps83-169-46-66.dedicated.hosteurope.de solid[19872]: at Server.listen (net.js:1485:7)
Jun 15 11:10:25 lvps83-169-46-66.dedicated.hosteurope.de solid[19872]: at bin (/opt/node_8.15.1_64/lib/node_modules/solid-server/bin/lib/st$
Jun 15 11:10:25 lvps83-169-46-66.dedicated.hosteurope.de solid[19872]: at Command.start.action (/opt/node_8.15.1_64/lib/node_modules/solid-$
Jun 15 11:10:25 lvps83-169-46-66.dedicated.hosteurope.de solid[19872]: at Command.listener (/opt/node_8.15.1_64/lib/node_modules/solid-serv$
Jun 15 11:10:25 lvps83-169-46-66.dedicated.hosteurope.de solid[19872]: at emitTwo (events.js:126:13)
Jun 15 11:10:25 lvps83-169-46-66.dedicated.hosteurope.de solid[19872]: at Command.emit (events.js:214:7)
Jun 15 11:10:25 lvps83-169-46-66.dedicated.hosteurope.de solid[19872]: at Command.parseArgs (/opt/node_8.15.1_64/lib/node_modules/solid-ser$
Jun 15 11:10:25 lvps83-169-46-66.dedicated.hosteurope.de solid[19872]: at Command.parse (/opt/node_8.15.1_64/lib/node_modules/solid-server/$
```

anything a pro would see I don' t see ?
let me ask another question.
I know the standard port for solid is 8443. but then not even the manual start works. with port 443 at least as said it works manual. it' s a public root-machine with cert and wildcard-cert. isn' t 443 the standard ssl-port ?
....
EDIT: I' m a step further, service is running at 8443 correct, but browser with URL shows apache standard site. how do I tell the system to deliver the solid-server ?
....
EDIT2: solidweb.org:8443 now works. how can I forward so that I don' t need the port in the URL ? will check the config at the provider, keep you updated and close this issue in time.

**Comment by ewingson** [comment]
fyi: got `solidweb.org:8443` working but wanna achive `solidweb.org`. gonna close it.
