### ISSUE TITLE
NSS needs node.js > 8

### ISSUE THREAD

**Issue by y0va** [solid/node-solid-server#1330]
We lately tried to install NSS with node.js 8, which resulted in a server which doesn't talk at all on it's public port. In [the docs on the inrupt page](https://solid.inrupt.com/docs/installing-running-nss) it's mentioned in the first sentence that node.js 8 would be sufficient. Maybe it works with 10, but we haven't tried.

I haven't found the sources for that text on github, fell free to move this issue to the appropriate place.

**Comment by megoth** [comment]
The [.nvmrc file](https://github.com/solid/node-solid-server/blob/master/.nvmrc) sets 8.16.0 as the default version of Node, might want to change that as well.

**Comment by dmitrizagidulin** [comment]
I'm not sure this is a Node version issue. Being able to listen on a public port is a general Unix-y root permission issue. Are you using a reverse proxy such as Nginx or Apache in front of your Solid server? (Or, if you're testing locally, does your node-solid-server user have root permission?)

**Comment by y0va** [comment]
This test was done without any reverse proxy on a remote VM.
With nodes.js 8 the port was open, but completely silent.
When we changed to node.js 12 (via nvm) the communications over the standard port worked like a charm. As this was the only thing we changed for making nss work, it's very unlikely any permission issues nor routing issues  had been involved.

**Comment by jaxoncreed** [comment]
Either way, we should update the .nvmrc file

**Comment by y0va** [comment]
Found that I had my dev server still running with node 8. Probably this intrusion was stemming from running this old version:

``` 
  solid:accounts Account 148.251.175.146 is available (for /) +1h
  solid:server [ '148.251.175.146', '80' ] => https://148.251.175.146,80:443/ +4m
  solid:server [ '148.251.175.146', '80' ] => https://148.251.175.146,80:443/ +10m
  solid:accounts Account 148.251.175.146 is available (for /) +32m
  solid:accounts Account 148.251.175.146 is available (for /) +3h
  solid:server [ '148.251.175.146', '80' ] => https://148.251.175.146,80:443/ +46m
  solid:ACL FetchError: request to https://148.251.175.146/upgrade.aspx.acl failed, reason: Hostname/IP does not match certificate's altnames: IP: 148.251.175.146 is not in the cert's list:
  solid:ACL     at ClientRequest.<anonymous> (/src/node-solid-server/node_modules/node-fetch/lib/index.js:1455:11)
  solid:ACL     at ClientRequest.emit (events.js:197:13)
  solid:ACL     at TLSSocket.socketErrorListener (_http_client.js:397:9)
  solid:ACL     at TLSSocket.emit (events.js:197:13)
  solid:ACL     at emitErrorNT (internal/streams/destroy.js:82:8)
  solid:ACL     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
  solid:ACL     at processTicksAndRejections (internal/process/next_tick.js:76:17) +18m
  solid:ACL Append access denied to (none): 500 - request to https://148.251.175.146/upgrade.aspx.acl failed, reason: Hostname/IP does not match certificate's altnames: IP: 148.251.175.146 is not in the cert's list:  +1ms
  solid:server Error page because of: { [HTTPError: request to https://148.251.175.146/upgrade.aspx.acl failed, reason: Hostname/IP does not match certificate's altnames: IP: 148.251.175.146 is not in the cert's list: ]
  name: 'HTTPError',
  message:
   "request to https://148.251.175.146/upgrade.aspx.acl failed, reason: Hostname/IP does not match certificate's altnames: IP: 148.251.175.146 is not in the cert's list: ",
  status: 500 } +0ms
TypeError: Cannot read property 'split' of undefined
    at /src/node-solid-server/lib/create-server.js:92:37
    at Layer.handle [as handle_request] (/src/node-solid-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/src/node-solid-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/src/node-solid-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/src/node-solid-server/node_modules/express/lib/router/layer.js:95:5)
    at /src/node-solid-server/node_modules/express/lib/router/index.js:281:22
    at param (/src/node-solid-server/node_modules/express/lib/router/index.js:354:14)
    at param (/src/node-solid-server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/src/node-solid-server/node_modules/express/lib/router/index.js:410:3)
    at next (/src/node-solid-server/node_modules/express/lib/router/index.js:275:10)
  solid:server [ '148.251.175.146', '80' ] => https://148.251.175.146,80:443/ +26m
  solid:server [ '148.251.175.146', '80' ] => https://148.251.175.146,80:443/ +8m
  solid:server [ '148.251.175.146', '80' ] => https://148.251.175.146,80:443/ +44m
  solid:server [ '148.251.175.146' ] => https://148.251.175.146:443/ +54m
  solid:server [ '148.251.175.146' ] => https://148.251.175.146:443/TP/public/index.php +3m
  solid:server [ '148.251.175.146', '80' ] => https://148.251.175.146,80:443/ +691ms
  solid:server [ '148.251.175.146' ] => https://148.251.175.146:443/ +46m
  solid:server [ 'abodxeycuklpva2v.onion' ] => https://abodxeycuklpva2v.onion:443/ +2m
  solid:server [ 'snuffqtsxrtwuhmm.onion' ] => https://snuffqtsxrtwuhmm.onion:443/ +205ms
  solid:server [ 'sadoavmxp3gm3zr3.onion' ] => https://sadoavmxp3gm3zr3.onion:443/ +204ms
  solid:server [ 'brutalmuv5rbwfnf.onion' ] => https://brutalmuv5rbwfnf.onion:443/ +6s
  solid:server [ 'qnrx2a4eb6ja4n6h.onion' ] => https://qnrx2a4eb6ja4n6h.onion:443/ +25s
  solid:server [ 'girlr7i4ptur3lpw.onion' ] => https://girlr7i4ptur3lpw.onion:443/ +3s
  solid:server [ 'deeppornx5rnxn5j.onion' ] => https://deeppornx5rnxn5j.onion:443/ +1s
  solid:server [ 'slavegl5jgdo2pbk.onion' ] => https://slavegl5jgdo2pbk.onion:443/ +4s
  solid:server [ 'breathrzhfvcggku.onion' ] => https://breathrzhfvcggku.onion:443/ +40s
  solid:server [ 'p5bzaqzsyptmszyiikbao3iclo5aqjvuj7pvyakoeluppgxni2oq2aqd.onion' ] => https://p5bzaqzsyptmszyiikbao3iclo5aqjvuj7pvyakoeluppgxni2oq2aqd.onion:443/ +24s
  solid:server [ 'dedsecq3dx2zfaiz.onion' ] => https://dedsecq3dx2zfaiz.onion:443/ +1s
  solid:server [ '148.251.175.146' ] => https://148.251.175.146:443/ +56m
TypeError: Cannot read property 'split' of undefined
    at /src/node-solid-server/lib/create-server.js:92:37
    at Layer.handle [as handle_request] (/src/node-solid-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/src/node-solid-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/src/node-solid-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/src/node-solid-server/node_modules/express/lib/router/layer.js:95:5)
    at /src/node-solid-server/node_modules/express/lib/router/index.js:281:22
    at param (/src/node-solid-server/node_modules/express/lib/router/index.js:354:14)
    at param (/src/node-solid-server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/src/node-solid-server/node_modules/express/lib/router/index.js:410:3)
    at next (/src/node-solid-server/node_modules/express/lib/router/index.js:275:10)
  solid:server [ '148.251.175.146' ] => https://148.251.175.146:443/index.php +1h
  solid:server [ '148.251.175.146' ] => https://148.251.175.146:443/phpmyadmin/index.php +320ms
  solid:server [ '148.251.175.146' ] => https://148.251.175.146:443/TP/public/index.php +1h
  solid:server [ '148.251.175.146', '80' ] => https://148.251.175.146,80:443/ +19m
TypeError: Cannot read property 'split' of undefined
    at /src/node-solid-server/lib/create-server.js:92:37
    at Layer.handle [as handle_request] (/src/node-solid-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/src/node-solid-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/src/node-solid-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/src/node-solid-server/node_modules/express/lib/router/layer.js:95:5)
    at /src/node-solid-server/node_modules/express/lib/router/index.js:281:22
    at param (/src/node-solid-server/node_modules/express/lib/router/index.js:354:14)
    at param (/src/node-solid-server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/src/node-solid-server/node_modules/express/lib/router/index.js:410:3)
    at next (/src/node-solid-server/node_modules/express/lib/router/index.js:275:10)
  solid:server [ '148.251.175.146', '80' ] => https://148.251.175.146,80:443/ +27m
  solid:server [ '148.251.175.146' ] => https://148.251.175.146:443/ +1h
  solid:accounts Account 148.251.175.146 is available (for /) +544ms
  solid:accounts Account 148.251.175.146 is available (for /) +33m
Terminated
```

**Comment by jaxoncreed** [comment]
@y0va It's possible but not certain that that would be caused by your node version. Does it work when you switch to a more recent version?

**Comment by y0va** [comment]
Yes, on node 12 it runs fine so far.

**Comment by melvincarvalho** [comment]
Node 8 is now [end of life](https://blog.risingstack.com/update-nodejs-8-end-of-life-no-support/)

**Comment by jaxoncreed** [comment]
I've updated the package.json in version 5.2.3
