### ISSUE TITLE
5.3.0 upgrade notes do not seem to be correct

### ISSUE THREAD

**Issue by bourgeoa** [solid/node-solid-server#1444]
@michielbdejong 
On an existing running server : if you delete `.db/oidc/op/provider.json` it is not re-created.

solid.community:8443 had the following provider.json : (hereunder the first lines) I kept it
```
  "issuer": "https://solid.community:8443",
  "jwks_uri": "https://solid.community:8443/jwks",
  "response_types_supported": [
    "code",
    "code token",
    "code id_token",
    "id_token",
    "id_token token",
    "code id_token token",
    "none"
  ],
  "token_types_supported": [
    "legacyPop",
    "dpop"
  ],
  "response_modes_supported": [
    "query",
    "fragment"
  ],
  "grant_types_supported": [
    "authorization_code",
    "implicit",
    "refresh_token",
    "client_credentials"
  ],
  "subject_types_supported": [
    "public"
  ],

```
My own server, has a different structure : (with no` token_types_supported`)
```
{
  "issuer": "https://bourgeoa.ga:8530",
  "authorization_endpoint": "https://bourgeoa.ga:8530/authorize",
  "token_endpoint": "https://bourgeoa.ga:8530/token",
  "userinfo_endpoint": "https://bourgeoa.ga:8530/userinfo",
  "jwks_uri": "https://bourgeoa.ga:8530/jwks",
  "registration_endpoint": "https://bourgeoa.ga:8530/register",
  "response_types_supported": [
    "code",
    "code token",
    "code id_token",
    "id_token",
    "id_token token",
    "code id_token token",
    "none"
  ],
  "response_modes_supported": [
    "query",
    "fragment"
  ],
  "grant_types_supported": [
    "authorization_code",
    "implicit",
    "refresh_token",
    "client_credentials"
  ],
  "subject_types_supported": [
    "public"
  ],

```

**Comment by michielbdejong** [comment]
Ah, thanks for reporting! Not sure where the difference comes from. I just tried it again on localhost and after restarting NSS (with `DEBUG=*`) I saw:
```sh
  solid:authentication No provider keys found, generating fresh ones +11ms
  solid:authentication Provider keychain initialized +714ms
  solid:authentication Not sleeping before client registration... +1ms
  solid:authentication Client fetched for issuer https://localhost:8443 +147ms
  solid:authentication Local RP client initialized +0ms
```
and .db/oidc/op/provider.json was recreated without problem. Can you restart NSS with .db/oidc/op/provider.json and `DEBUG=*` set as env var, and then paste the first messages it outputs?

**Comment by bourgeoa** [comment]
Here are the results : 
```
root@solid:/home/solid/nss-test# bin/solid start DEBUG=*
Solid server (v5.3.1) running on https://localhost:8443/
Press <ctrl>+c to stop
  solid:index Looking for index in / +0ms
  solid:get / on bourgeoa.solid.community +170ms
  solid:get    sending data browser file: /home/solid/nss-test/node_modules/mashlib/dist/index.html +38ms
  solid:get / on bourgeoa.solid.community +644ms
  solid:get /profile/card on bourgeoa.solid.community +98ms
  solid:get /favicon.ico on bourgeoa.solid.community +160ms
  solid:get /settings/publicTypeIndex.ttl on bourgeoa.solid.community +226ms
  solid:get / on solid.community +8s
  solid:get / on bourgeoa.solid.community +482ms
^C
Solid stopped.

```
There are no initialization steps.

**Comment by ewingson** [comment]
@michielbdejong @bourgeoa 

no idea if that helps, for upgrading to 5.4.0 I did a `npm -g upgrade solid-server` and did not touch `provider.json` which I include below.....
```
{
  "issuer": "https://solidweb.org",
  "jwks_uri": "https://solidweb.org/jwks",
  "response_types_supported": [
    "code",
    "code token",
    "code id_token",
    "id_token",
    "id_token token",
    "code id_token token",
    "none"
  ],
  "token_types_supported": [
    "legacyPop",
    "dpop"
  ],
  "response_modes_supported": [
    "query",
    "fragment"
  ],
  "grant_types_supported": [
    "authorization_code",
    "implicit",
    "refresh_token",
    "client_credentials"
  ],
  "subject_types_supported": [
    "public"
  ],
```

**Comment by bourgeoa** [comment]
@ewingson @michielbdejong
 
Thanks @ewingson
Historically the solid.community is started from a git repo. It is not upgraded from npm

So the upgrade process used is along those lines :
- git branch (to check the actual branch, actually locally it is running on v.5.2.3-branch created from tag v5.2.3)
- git checkout master
- git pull
- npm install
- pm2 restart solid (or bin/solid start)

**Comment by bourgeoa** [comment]
Today's update of solid.community to NSS v5.4.0 did not upgrade the provider.json file.
I had to reinstate the old provider.json kept as a backup
```
root@solid:/home/solid/node-solid-server# rm .db/oidc/op/provider.json
root@solid:/home/solid/node-solid-server# npm install
......
root@solid:/home/solid/node-solid-server# bin/solid start DEBUG=*
Solid server (v5.4.0) running on https://localhost:443/
Press <ctrl>+c to stop
  solid:get /robots.txt on titleistfairwaywood.solid.community +0ms
  solid:get / on titleistfairwaywood.solid.community +809ms
  solid:get /profile/card on bourgeoa.solid.community +11s
  solid:get    sending data browser file: /home/solid/node-solid-server/node_modules/mashlib/dist/index.html +4ms
  solid:get /profile/card on bourgeoa.solid.community +3s
  solid:get /settings/publicTypeIndex.ttl on bourgeoa.solid.community +484ms
  solid:get /favicon.ico on bourgeoa.solid.community +244ms
  solid:get / on solid.community +8s
  solid:get /Team/SolidOs%20team%20chat/2020/07/15/chat.ttl on solidos.solid.community +28s
  solid:get /Team/SolidOs%20team%20chat/2020/07/16/chat.ttl on solidos.solid.community +104ms
  solid:get /Team/SolidOs%20team%20chat/2020/07/17/chat.ttl on solidos.solid.community +1s
  solid:get GET -- Error: 404 Can't find file requested: [object Object] +2ms
^C
Solid stopped.
root@solid:/home/solid/node-solid-server# cd .db/oidc/op
root@solid:/home/solid/node-solid-server/.db/oidc/op# ls
clients  codes  old.provider.json  refresh  tokens
root@solid:/home/solid/node-solid-server/.db/oidc/op# cp old.provider.json provider.json
root@solid:/home/solid/node-solid-server# pm2 restart solid.community


```

**Comment by michielbdejong** [comment]
I also had a look just now, and found:
```sh
Solid server (v5.4.0) running on https://localhost:443/
Press <ctrl>+c to stop
  solid:authentication No provider keys found, generating fresh ones +19ms
  solid:authentication TypeError: crypto__default.generateKeyPairSync is not a function
  solid:authentication     at Function.generateKey (/home/solid/node-solid-server/node_modules/@peculiar/webcrypto/build/webcrypto.js:1042:38)
  solid:authentication     at RsaSsaProvider.onGenerateKey (/home/solid/node-solid-server/node_modules/@peculiar/webcrypto/build/webcrypto.js:1231:37)
  solid:authentication     at RsaSsaProvider.generateKey (/home/solid/node-solid-server/node_modules/webcrypto-core/build/webcrypto-core.js:112:35)
  solid:authentication     at SubtleCrypto.generateKey (/home/solid/node-solid-server/node_modules/webcrypto-core/build/webcrypto-core.js:753:39)
  solid:authentication     at RsaKeyPair.generateKey (/home/solid/node-solid-server/node_modules/@solid/oidc-auth-manager/node_modules/@solid/keychain/src/algorithms/RsaKeyPair.js:56:8)
  solid:authentication     at Function.generateKey (/home/solid/node-solid-server/node_modules/@solid/oidc-auth-manager/node_modules/@solid/keychain/src/KeyChain.js:46:22)
  solid:authentication     at Promise.all.Object.keys.map.key (/home/solid/node-solid-server/node_modules/@solid/oidc-auth-manager/node_modules/@solid/keychain/src/KeyChain.js:144:27)
  solid:authentication     at Array.map (<anonymous>)
  solid:authentication     at KeyChain.rotate (/home/solid/node-solid-server/node_modules/@solid/oidc-auth-manager/node_modules/@solid/keychain/src/KeyChain.js:138:27)
  solid:authentication     at Promise.all.Object.keys.map.key (/home/solid/node-solid-server/node_modules/@solid/oidc-auth-manager/node_modules/@solid/keychain/src/KeyChain.js:159:23) +6ms
```

From https://stackoverflow.com/questions/53867515/typeerror-generatekeypairsync-not-a-function, it's because the server was still running node version 8, we need at least 10. I'll install nvm on solid.community so we can update the node version more easily.
