### ISSUE TITLE
500 error on token endpoint

### ISSUE THREAD

**Issue by michielbdejong** [solid/node-solid-server#1445]
```sh
curl -d "grant_type=refresh_token&refresh_token=thisIsARefreshToken&client_id=5897c2df511eaad24ac39999c0536ec6" -v -k -X POST https://localhost:8443/token -H "DPoP: eyJhbGciOiJSUzI1NiIsInR5cCI6ImRwb3Arand0IiwiandrIjp7Imt0eSI6IlJTQSIsImtpZCI6IjVmMVFZcmppOGItWWdGczBIbmNuam52ZmZ4X0RKdTU3R1hDeXlLMDlBakUiLCJ1c2UiOiJzaWciLCJhbGciOiJSU0EiLCJlIjoiQVFBQiIsIm4iOiJ5d3hpTnFXUkpFblF3RkpBeDlJVFFkeERKVWw2dzdIV3dXZTZVOUtQYnYzNEZ0NzJVd21iZHA2dTcwb1FvMkFQVkozMlNjbkJOeV80S2FuMU5VQktRWW12T1k2VFdBQWpPMzRBY0FTamZ6aV90S0xzTlY1ZGhTdE5tTWlzTUc3c2c4c2drWndzOFd2R29rX2tTNUNTM2lVQmVnVlhacmhZTDQwb1RNSjdmNWFERmg2cUJhbHZpVms5djliMEp1UklYNWNDYmFfU1RyUE9CZlZ5Mk5YNHFuRmdtQ2xqODhDMkFvY1BBVThFYW9ub0FiUzlzRGtfTTY5d2hDbndRTGJBU0ZjajhIREE5QTZDRmhJYnBqX0F2dnFBUnJwRnpOZlhQZXdvNHVIOVpuby1RUEgxaTdBbmVBYmZDZnlWdXIwT3RFcHhvUWNZbFh6aVE1c3NRbGs3THcifX0.eyJodHUiOiJodHRwczovL2xvY2FsaG9zdDo4NDQzL3Rva2VuIiwiaHRtIjoiUE9TVCIsImp0aSI6IjRiOTU2ZmI1LTdkYTItNDk0ZS04OTFhLTg0NzYyNjUxNjlkNSIsImlhdCI6MTU5NDgxMDk4MiwiZXhwIjoxNTk0ODE0NTgyfQ.MOHhHoC2vhYWIhHTdgp0vLRirTi1XAjJ-QcIwwpZBR6suvMA19yBPeSFtmPjIlS0_EKlrVzqtiqtB9KmGwUsg6HSRi4H3u4jEbu837P_VFRzILPuupi_S3Y--RrXJ04lV6PvE-OI5Mv7sSnWXjRfEfKUnebB2XBeOTIbmNIwS3jbqjwYexaMm3ZTWFlZE5Nq_vh0BrX61fAgxRROJqQld-f7EUhdUxUnhY0peXstNVaX8wW1p2yxTM23ihJPgvbjYjTrNE-DxuyD-Y6W0UUngmmryh-0Rml3FUUGzaU8k_9s5Sul4HmRh0otpeAhPb9WqXum-P-YWSB8EFQ3yoe5mQ" -H "Authorization: Basic NTg5N2MyZGY1MTFlYWFkMjRhYzM5OTk5YzA1MzZlYzY6OTc0ZjUxNmQ4YzJkZDUzYjRhYzQ3NzhlMGVmYWE0NWE=" -H "content-type: application/x-www-form-urlencoded"
```
returns a 500 Internal Server Error.

**Comment by michielbdejong** [comment]
```sh
error TypeError: AccessToken.refresh is not a function
    at TokenRequest.refreshTokenGrant (/Users/michiel/gh/solid/node-solid-server/node_modules/@solid/oidc-auth-manager/node_modules/@solid/oidc-op/src/handlers/TokenRequest.js:504:24)
    at grant (/Users/michiel/gh/solid/node-solid-server/node_modules/@solid/oidc-auth-manager/node_modules/@solid/oidc-op/src/handlers/TokenRequest.js:445:22)
```
Mind this was caught in a node-module of a node-module, `./node_modules/@solid/oidc-auth-manager/node_modules/@solid/oidc-op`

**Comment by michielbdejong** [comment]
ok, looks like I was probably using the wrong grant type. https://github.com/solid/authentication-panel/blob/master/oidc-authentication.md#basic-flow suggests I should try using `authorization_code` instead.
