### ISSUE TITLE
JSON-LD related tests failing in update-deps branch

### ISSUE THREAD

**Issue by michielbdejong** [solid/node-solid-server#1455]
Set up your [mashlib-dev](https://github.com/solid/mashlib-dev) with the `update-deps` branches of node-solid-server and of rdflib. Run `npx lerna bootstrap --force-local` so they link up, and then in ./workspaces/node-solid-server, run:
```sh
DEBUG=* ./node_modules/.bin/mocha  test/integration/formats-test.js
```
You'll see 3 out of 4 JSON-LD tests failing:
```
formats
    JSON-LD
      1) should return JSON-LD document if Accept is set to only application/ld+json
      2) should return the container listing in JSON-LD if Accept is set to only application/ld+json
      ✓ should prefer to avoid translation even if type is listed with less priority
      3) should return JSON-LD document if Accept is set to application/ld+json and other types

**Comment by michielbdejong** [comment]
Running `npm run watch` for rdflib in a separate window, I'm seeing it hit https://github.com/linkeddata/rdflib.js/blob/update-deps/src/convert.js#L25-L27. To reproduce the error that gets thrown there:
```sh
node -e "require('jsonld').fromRDF('<https://localhost:8443/patch-5-initial.ttl#Iss1408851516666> <http://www.w3.org/2005/01/wf/flow#assignee> <https://localhost:8443/patch-5-initial.ttl#TBL> . <https://localhost:8443/patch-5-initial.ttl#Iss1408851516666> <https://localhost:8443/patch-5-initial.ttl#ppp> "123"^^<http://www.w3.org/2001/XMLSchema#integer> .', { format: 'application/nquads' }, (err, result) => { console.log({ err, result }) })"
{
  err: JsonLdError [jsonld.ParseError]: Error while parsing N-Quads; invalid quad.
      at _parseNQuads (/Users/michiel/gh/solid/mashlib-dev/workspaces/node-solid-server/node_modules/jsonld/js/jsonld.js:6964:13)
      at /Users/michiel/gh/solid/mashlib-dev/workspaces/node-solid-server/node_modules/jsonld/js/jsonld.js:881:17
      at processTicksAndRejections (internal/process/task_queues.js:79:11) {
    details: { line: 1 }
  },
  result: undefined
}
```

**Comment by michielbdejong** [comment]
Ah, using the Promise interface for `jsonld.fromRDF` fixes the test.

**Comment by michielbdejong** [comment]
Fixed in https://github.com/linkeddata/rdflib.js/commit/44c269ce46f3fd125d76198c3fea2905c4b5bb87.
