### ISSUE TITLE
Error fetching "openid configuration" when running Solid using docker 🐳 and outdated documentation 📜

### ISSUE THREAD

**Issue by vemonet** [solid/node-solid-server#1472]
### Running Solid using docker

I am trying to deploy Solid using Docker on top [nginx-proxy](https://github.com/nginx-proxy/nginx-proxy) + [letsencrypt-nginx-companion](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion)

I used this docker-compose as example: https://github.com/angelo-v/docker-solid-server/blob/master/examples/docker-compose.nginx.yml

Here is my version:

```yaml
version: "3"
services:
  solid:
    image: nodesolidserver/node-solid-server:latest
    # image: aveltens/solid-server:latest
    container_name: solid-server
    restart: unless-stopped
    ports:
      - 8443:8443
    environment:
      - "SOLID_SERVER_URI=https://solid.fairuse.org"
      - "SOLID_SSL_KEY=/opt/solid/certs/solid.fairuse.org/key.pem"
      - "SOLID_SSL_CERT=/opt/solid/certs/solid.fairuse.org/fullchain.pem"
      - "VIRTUAL_HOST=solid.fairuse.org"
      - "LETSENCRYPT_HOST=solid.fairuse.org"
      - "VIRTUAL_PORT=8443"
    volumes:
      - /data/certs:/opt/solid/certs
```

> At the moment I do not use shared volumes, to be sure the Solid server use a clean storage and avoid conflicts

### Issue at runtime

Same issue raised when trying the 2 images: `solid:authentication Error registering a new client:  { Error: Error fetching openid configuration: 502 Bad Gateway` 

Here some more details that could help understanding the issue origin:

* The provided certs worked fine apparently, but the node server does not start. 
* I could not find documentation about `openid configuration`, neither existing issues 
* The [README documentation](https://github.com/solid/node-solid-server) mostly mention getting around SSL certificates issues, which seems to be working in this case
* Note that I have multiple other services running without issues with the nginx-proxy same setup

### Missing config.json

The [README documentation](https://github.com/solid/node-solid-server) mention multiple times a `config.json` file which is not present in the Docker container  (but it seems to be important)

Results of `ls -a` in `/opt/solid`:

```bash
.db                       checks.sh                 create-temporary-cert.sh  entrypoint.sh             solid-temporary.key
certs                     config                    data                      solid-temporary.crt
```

And in `/opt/solid/config` (templates and views folder, no config.json)

```bash
/opt/solid/config $ ls -a templates/
emails       new-account  server

/opt/solid/config $ ls -a views/
account  auth     shared
```

### Documentation seems outdated

* The [GitHub README documentation](https://github.com/solid/node-solid-server) still uses `/usr/src/app` as home path in the Docker, but the latest images use `/opt/solid`, so it might be outdated. 

* The documentation on [solidproject.org](https://solidproject.org/for-developers/pod-server) is only explaining how to install solid directly on a local machine or on the server, but no documentation related to deploying using Containers (could be useful as now containers and Kubernetes start to be really popular when it comes to deploy web services)

### Full error logs

Here is the full logs:

```
checking preconditions...
✓ /opt/solid/certs/solid.fairuse.org/key.pem is accessible by node
✓ /opt/solid/certs/solid.fairuse.org/fullchain.pem is accessible by node
Finished: SUCCESS
TIP create a config.json: `$ solid init`
2020-09-03T07:40:05.876Z solid:settings Server URI: https://solid.fairuse.org
2020-09-03T07:40:05.876Z solid:settings Auth method: oidc
2020-09-03T07:40:05.876Z solid:settings Strict origins: true
2020-09-03T07:40:05.876Z solid:settings Allowed origins: 
2020-09-03T07:40:05.876Z solid:settings Db path: ./.db
2020-09-03T07:40:05.876Z solid:settings Config path: ./config
2020-09-03T07:40:05.876Z solid:settings Suffix Acl: undefined
2020-09-03T07:40:05.876Z solid:settings Suffix Meta: undefined
2020-09-03T07:40:05.876Z solid:settings Allow WebID authentication: true
2020-09-03T07:40:05.876Z solid:settings Live-updates: true
2020-09-03T07:40:05.876Z solid:settings Multi-user: false
2020-09-03T07:40:05.876Z solid:settings Suppress default data browser app: undefined
2020-09-03T07:40:05.876Z solid:settings Default data browser app file path: default
2020-09-03T07:40:05.890Z solid:settings CORS proxy listening at /xss?uri={uri}
2020-09-03T07:40:05.900Z solid:settings Base URL (--mount): /
2020-09-03T07:40:05.900Z solid:settings SSL Private Key path: /opt/solid/certs/solid.fairuse.org/key.pem
2020-09-03T07:40:05.900Z solid:settings SSL Certificate path: /opt/solid/certs/solid.fairuse.org/fullchain.pem
Solid server (5.5.2) running on https://localhost:8443/
Press <ctrl>+c to stop
2020-09-03T07:40:05.920Z solid:authentication No provider keys found, generating fresh ones
2020-09-03T07:40:06.622Z solid:authentication Provider keychain initialized
2020-09-03T07:40:06.623Z solid:authentication Not sleeping before client registration...
2020-09-03T07:40:06.625Z solid:authentication Client not present for issuer https://solid.fairuse.org, initializing new client
2020-09-03T07:40:06.626Z solid:authentication Registering new client for issuer  https://solid.fairuse.org
2020-09-03T07:40:06.698Z solid:authentication Error registering a new client:  { Error: Error fetching openid configuration: 502 Bad Gateway
    at /usr/local/lib/node_modules/solid-server/node_modules/@solid/oidc-rp/src/onHttpError.js:32:17
    at process._tickCallback (internal/process/next_tick.js:68:7)
  response:
   Response {
     size: 0,
     timeout: 0,
     [Symbol(Body internals)]: { body: [PassThrough], disturbed: false, error: null },
     [Symbol(Response internals)]:
      { url:
         'https://solid.fairuse.org/.well-known/openid-configuration',
        status: 502,
        statusText: 'Bad Gateway',
        headers: [Headers],
        counter: 0 } },
  statusCode: 502 }
2020-09-03T07:40:06.702Z solid:authentication Error initializing local RP client:  { Error: Error fetching openid configuration: 502 Bad Gateway
    at /usr/local/lib/node_modules/solid-server/node_modules/@solid/oidc-rp/src/onHttpError.js:32:17
    at process._tickCallback (internal/process/next_tick.js:68:7)
  response:
   Response {
     size: 0,
     timeout: 0,
     [Symbol(Body internals)]: { body: [PassThrough], disturbed: false, error: null },
     [Symbol(Response internals)]:
      { url:
         'https://solid.fairuse.org/.well-known/openid-configuration',
        status: 502,
        statusText: 'Bad Gateway',
        headers: [Headers],
        counter: 0 } },
  statusCode: 502 }
```

### Machine details

CentOS 7

Docker version:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
```

**Comment by bourgeoa** [comment]
For config.file in Docker see comments in issue #1450

**Comment by michielbdejong** [comment]
I noticed `- "VIRTUAL_PORT=8443"`, shouldn't that be port 443?
And can you see `https://localhost:8443/.well-known/openid-configuration` from inside the container?

**Comment by vemonet** [comment]
I am a bit skeptical about https://localhost:8443

```bash
wget https://localhost:8443/.well-known/openid-configuration
Connecting to localhost:8443 (127.0.0.1:8443)
ssl_client: localhost: name `localhost' not present in server certificate
```

I also tried 443, but in the case of solid it is 8443 that is exposed

**Comment by vemonet** [comment]
Resolved it by enforcing HTTPS protocol for nginx in the environment variables:

```yaml
environment:
  - VIRTUAL_PROTO=https
```

Thanks a lot for the help!
