### ISSUE TITLE
solid init fails

### ISSUE THREAD

**Issue by boblund** [solid/node-solid-server#1479]
Did (with node 13.6.0, npm 6.13.4, Mac OS 10.14.6):

>sudo npm install -g solid-server
>solid init

And got:

node-solid-server: solid init
internal/modules/cjs/loader.js:628
  throw e;
  ^

Error: No valid exports main found for '/usr/local/lib/node_modules/solid-server/node_modules/colorette'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/solid-server/bin/lib/cli-utils.js:2:29)
    at Module._compile (internal/modules/cjs/loader.js:1144:30) {
  code: 'MODULE_NOT_FOUND'
}

**Comment by boblund** [comment]
I fixed the above by downgrading the required colorette dependency to 1.2.0. A web search suggested that node 14 was required for the newer version of colorette.

I then ran into another problem:

/usr/local/lib/node_modules/solid-server/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1060:16)
    at Module._compile (internal/modules/cjs/loader.js:1108:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/solid-server/node_modules/solid-rest/src/rest.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)

A web search suggests that the JavaScript construct being complained about requires Node 14. So I guess Solid requires Node 14? If so, maybe the install section could reflect that.

**Comment by bourgeoa** [comment]
Interesting. I also found that node 13 has compatibility issues with some mom packages
