### ISSUE TITLE
Token refresh 500

### ISSUE THREAD

**Issue by ianconsolata** [solid/node-solid-server#1588]
@michielbdejong I am seeing 500s on the `/token` endpoint when `solid-auth-fetcher` tries to renew the token, as well as a 401. The server logs are set to  verbose, but don't show the 500, only the 401. I am not sure which headers I can safely include in a message, so opted to not include any. Do you have any suggestions about how to add additional logging to debug this issue more? 

Client requests / responses:

> POST https://myunderstory.com/token 500
> data:
> grant_type: refresh_token
> refresh_token: REDACTED
> client_id: REDACTED
> 
> GET https://ian.myunderstory.com/inbox/ 401 

Server logs:

> 2021-04-02T21:24:54.369Z solid:server Display login-required for https://ian.myunderstory.com/private/apps/understory/garden/workspace/default/prefs.ttl
> 2021-04-02T21:24:56.115Z solid:ACL Using ACL https://ian.myunderstory.com/private/.acl for ./apps/understory/garden/workspace/default/prefs.ttl
> 2021-04-02T21:24:56.115Z solid:ACL    1  default authentications about <https://ian.myunderstory.com/private/> in <https://ian.myunderstory.com/private/.acl>
> 2021-04-02T21:24:56.162Z solid:ACL accessDenied: checking access to <https://ian.myunderstory.com/private/apps/understory/garden/workspace/default/prefs.ttl> by null and origin <https://understory.garden>
> 2021-04-02T21:24:56.162Z solid:ACL    1  default authentications about <https://ian.myunderstory.com/private/> in <https://ian.myunderstory.com/private/.acl>
> 2021-04-02T21:24:56.162Z solid:ACL    Checking auth <https://ian.myunderstory.com/private/.acl#owner> with agent null
> 2021-04-02T21:24:56.162Z solid:ACL     Agent or group: Fail: not public and not logged on.
> 2021-04-02T21:24:56.162Z solid:ACL      The agent/group check fails
> 2021-04-02T21:24:56.162Z solid:ACL       Check failed: User Unauthorized
> 2021-04-02T21:24:56.162Z solid:ACL accessDenied: modeURIorReasons: ["User Unauthorized"]
> 2021-04-02T21:24:56.162Z solid:ACL  checking <http://www.w3.org/ns/auth/acl#Read>
> 2021-04-02T21:24:56.162Z solid:ACL   MODE REQUIRED NOT ALLOWED: <http://www.w3.org/ns/auth/acl#Read> Denying with User Unauthorized
> 2021-04-02T21:24:56.162Z solid:ACL Read access denied to (none): undefined - Unauthorized
> 2021-04-02T21:24:56.162Z solid:server Error page because of: { Error: Unauthorized
>     at AuthenticatedRequest.unauthorized (/opt/solid/node_modules/@solid/oidc-rs/src/AuthenticatedRequest.js:761:19)
>     at validateExpiry (/opt/solid/node_modules/@solid/oidc-rs/src/AuthenticatedRequest.js:627:22)
>   handled: true,
>   statusCode: 401,
>   realm: 'https://myunderstory.com',
>   error: 'invalid_token',
>   error_description: 'Access token is expired',
>   error_uri: undefined }

**Comment by bourgeoa** [comment]
What is your server version ? Refresh tooken has been implemented in the latest NSS v5.6.6.

**Comment by ianconsolata** [comment]
That sounds like it's probably the cause! Lemme update and see if that fixes things.
