### ISSUE TITLE
internal server error on /token

### ISSUE THREAD

**Issue by michielbdejong** [solid/node-solid-server#1613]
When [running the WAC test suite against CSS](https://github.com/solid/web-access-control-tests/blob/main/run-against-css.sh), a call is made to log in to https://solidcommunity.net/token and it returns a 500 error:

```sh
curl -v -X 'POST' -d 'grant_type=authorization_code&code_verifier=QQRrTzwMuBRoKAUFOZI5zRi7Qu0s193UxBZGcJepWItFPhbk2R&code=411d93b4086e1fd8d44904f3ea5888aa&redirect_uri=https%3A%2F%2Ftester&client_id=53bae6564353ea57c5d1caa066f8986f' -H 'DPoP: eyJhbGciOiJSUzI1NiIsInR5cCI6ImRwb3Arand0IiwiandrIjp7Imt0eSI6IlJTQSIsImtpZCI6IlB5UWkzYnE3eHkzbmliOFBiYTVra3Qybmt4T081M2VJeVlYT1N5Z3pXYXciLCJ1c2UiOiJzaWciLCJhbGciOiJSUzI1NiIsImUiOiJBUUFCIiwibiI6IjBoSGhka0staE5XR21iWHpCeVM5bkR6bkJqaXpNTWt0R0o1aHZMc3hKWnN3aW95SHVvSU43SDFEREEtbzhGNWh2UGhWZ3l5RjlycUxyemszcWZ5YXl6SjJHcXM0c0pGZEI4M1lBVDVnYzhqc2hqd0ZPZUItdGJCVGsyRW9VeGliUTl5cEFWOHdLdXRFNXJ4RWt2RjdwSjQwd09VMDhtdWxhSGEtVHN0U2RLUnYyRy01WkJDcTc0VE10dVRMWThaZXZMdzRHQ3cyWmZmSnNUSDJzMmtCWUw0YzhMdkVKcDZESm1lTXI1cktrOEhvRE03MFB2am5tVDBWR21KazN0RzJPZTlvSVR0Nld4NW5VNTdHS0ppMzdNYUtWeDZZTFBZS2RwdlJMZ1NvU2FvT1c5VTNkM2pkcW5XMWY4bDkzUGw0VTVZMkhUdFRYT2F1b3o2aUNKRWFQUSJ9fQ.eyJodHUiOiJodHRwczovL3NvbGlkY29tbXVuaXR5Lm5ldC90b2tlbiIsImh0bSI6IlBPU1QiLCJqdGkiOiI2MTgwYTU5NC05MmQxLTRhN2MtOWM2YS0xNmJiZTgxMzM3NjAiLCJpYXQiOjE2MzAzMzU4MjMsImV4cCI6MTYzMDMzOTQyM30.o1mQtUhqSUh6d1uigP9w2pKEr6TduqT6Y4NTHgvj7eKLZpU9nMNN6gfR6BMDWs50R5P4ABZ8G49OPFMIBQB9bbt5dqhZ6qoNUgpo2fcFbcpVaddUO5RZlB8R6CeYbWCoWutX_2URet_qDU46tR6yx1iaWGyVCX81ZhebE9_kQesT4D7OmHaHJPXlj3GGPEj-rit8z68CWJGbs3ISMM6OKR0Ybo89BspofWCGjNc7ghIauvoadbRh-rVTaGPNCpZeb6HpzHL600oVPHjQIAHU7sZH2NR_1BlPazhhEw6mzrzjECMOZVufcraDT4Dc1i68fPwqcEZjRe7iJr6AuE2fUA' -H 'content-type: application/x-www-form-urlencoded' -H 'Authorization: Basic NTNiYWU2NTY0MzUzZWE1N2M1ZDFjYWEwNjZmODk4NmY6MTQyODc1OTQyZmM1MTBjMjE2ZDY0ZjFkYTU3YzQxMTg=' https://solidcommunity.net/token
```

**Comment by michielbdejong** [comment]
trying to reproduce this locally now

**Comment by michielbdejong** [comment]
I'm reproducing this with https://solid-staging.pondersource.net which is running latest main of NSS with `npm ci` and with the workaround applied from https://github.com/solid/node-solid-server/issues/1609#issuecomment-908415958.

On my laptop I have latest main of web-access-control-tests with `npm ci` and running an adaptation of `./run-against-css.sh`.

Here is the call:
```sh

  SolidAuthFetcher curl -v -X 'POST' -d 'grant_type=authorization_code&code_verifier=aqz02XCN7QoIX32oOIXl5Lwm5GssBK33rpgWr8xPnnvAsKVRSV&code=5c9396f83aae245ee3ebc3dfed03c835&redirect_uri=https%3A%2F%2Ftester%2F&client_id=34597145aeab5518575e3f26b9734c3e' -H 'DPoP: eyJhbGciOiJSUzI1NiIsInR5cCI6ImRwb3Arand0IiwiandrIjp7Imt0eSI6IlJTQSIsImtpZCI6IkRPSzBleVVEbWRkYk16TVQ0MEJmNlNNVmxIUHdRb3ZaS1p6QmZ1ZHRGZFEiLCJ1c2UiOiJzaWciLCJhbGciOiJSUzI1NiIsImUiOiJBUUFCIiwibiI6InJONFRaNUpkZ20tLVJCTXowM281QU5Oc09IaEJKM1czWExiZGc5Q0VNMWxfRTJ0U0lyMktEU3h2OTZ3bzJtY2gxTWFaRklCWmtKRVFVemRBMDZ6Qmh3Y3ZvaVFzT3ctQlhvRHNPQlk4dHJ0THRUWTA2VHl4SkwySWY1S3ZiQjNkUVI5MDlObV9OOE9qd0VHVmNTMTVibjExdmJ2RFdXbng3R3pWa1BYQVFycWxvTjh0UVNEVlNKVVJnWm13UGtLLXJsSHUxSVBXNlRkSEZlNnNoQi1xZTdBS2x1LWxQZ0pPR1hpU1kybTFkaWpFVnh6NUE0YzZaQmhweUxMNVhEQzhUekZMNGptMzNGS2dMQlVXbzZmUFQtTTlUOE1qRTAtb1JETERad1NnVkVuUXZIdnE5WUZfa29Wb1AyVVFzODNOb1FfQUpjWHFWZXU2LUNITjhiVk9HdyJ9fQ.eyJodHUiOiJodHRwczovL3NvbGlkLXN0YWdpbmcucG9uZGVyc291cmNlLm5ldC90b2tlbiIsImh0bSI6IlBPU1QiLCJqdGkiOiJiNjQ3Y2M2NC00ZTg2LTQzOGMtYmMwMi1mMzVlMTRlZmFkNmUiLCJpYXQiOjE2MzAzOTgxOTMsImV4cCI6MTYzMDQwMTc5M30.C4Un-ks1-F-QwE6XzJto8K8E0oenA3RN_m6_mPPvXfEQVtykyJVooyIKmPEAX2VyIMf-w5wAu0EDUiWrYTw5Pn4NfFhhw8ZkiOADDGEYy71HR-JzdgBviPmnQvIQbMnMulvDHS0IPsSNOx2-_tkw-DhxkE3DYLybLgUybMZakpo9XXSQb7eJWODh7PyxFshvYIVgXWegeehNIdicjSxC0QHpcB9x0K_j8H17bfnPJskird2q60VeSd4KVLasN_G4EHSAUWCkeUMVum0OEON9Hg3Rx1FqLbJoQfSwHvv2s7nFDkyOa8B8r3Mh5qCt3EAUgYi4Yw_PDKyMajSqa_pIsQ' -H 'content-type: application/x-www-form-urlencoded' -H 'Authorization: Basic MzQ1OTcxNDVhZWFiNTUxODU3NWUzZjI2Yjk3MzRjM2U6MTk5ZmQ4NzIwMzVmZjliZjdlNDU2NjEzMzVmMzVhNmM=' https://solid-staging.pondersource.net/token
```

And here is the error from the NSS log:
```sh
TypeError: Cannot read property 'kty' of undefined
    at canonicalizeJwk (/root/solidos/workspaces/node-solid-server/node_modules/jwk-thumbprint/dist/src/index.js:6:17)
    at jwkThumbprintByEncoding (/root/solidos/workspaces/node-solid-server/node_modules/jwk-thumbprint/dist/src/index.js:31:24)
    at Function.issueForRequest (/root/solidos/workspaces/node-solid-server/node_modules/@solid/oidc-op/src/DpopAccessToken.js:120:12)
    at TokenRequest.includeAccessToken (/root/solidos/workspaces/node-solid-server/node_modules/@solid/oidc-op/src/handlers/TokenRequest.js:481:30)
    at /root/solidos/workspaces/node-solid-server/node_modules/@solid/oidc-op/src/handlers/TokenRequest.js:467:33
(node:43094) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:530:11)
    at ServerResponse.header (/root/solidos/workspaces/node-solid-server/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/root/solidos/workspaces/node-solid-server/node_modules/express/lib/response.js:170:12)
    at TokenRequest.internalServerError (/root/solidos/workspaces/node-solid-server/node_modules/@solid/oidc-op/src/handlers/BaseRequest.js:294:21)
    at TokenRequest.error (/root/solidos/workspaces/node-solid-server/node_modules/@solid/oidc-op/src/handlers/BaseRequest.js:284:12)
    at /root/solidos/workspaces/node-solid-server/node_modules/@solid/oidc-op/src/handlers/TokenRequest.js:43:17
(node:43094) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:43094) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```


[I have CSS checked out on my laptop with `npm ci` to latest `versions/2.0.0` branch which is the system-under-test but I don't think it plays a role here (I think the call to /token comes from web-access-control-tests).]

**Comment by michielbdejong** [comment]
Ah bummer, the trailing slash on the issuer broke it, it's now looking for https://solid-staging.pondersource.net//token instead of https://solid-staging.pondersource.net/token

**Comment by michielbdejong** [comment]
Undid it in my staging server, discussing in https://gitter.im/solid/solidcommunity.net to undo the change on solidcommunity.net
