### ISSUE TITLE
Server crashes on a GET with `Accept: *` header 

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/node-solid-server#301]
To reproduce:

```bash
curl -vk https://localhost:8443/profile/ -H 'Accept: *'
```

results in ldnode crash:

```
/Users/dmitri/code/_Solid/ldnode/lib/handlers/index.js:26
    if (requestedType.indexOf('text/html') !== 0) {
                     ^

TypeError: Cannot read property 'indexOf' of undefined
    at /Users/dmitri/code/_Solid/ldnode/lib/handlers/index.js:26:22
    at /Users/dmitri/code/_Solid/ldnode/lib/ldp.js:86:12
    at FSReqWrap.oncomplete (fs.js:82:15)
```

(Incidentally, it works fine if you do a GET with `Accept: */*`, but we should probably fix the crash part)

**Comment by dmitrizagidulin** [comment]
Fixed, closing.
