### ISSUE TITLE
Missing dependency on 'commander' module

### ISSUE THREAD

**Issue by fragglet** [solid/node-solid-server#415]
Following the install instructions I hit the following error; `npm install commander` fixed it. I think it needs to be added as a dependency?

```
Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/fra/.npm-global/lib/node_modules/solid-server/bin/solid.js:3:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by fragglet** [comment]
This was already fixed in 2123bc466f5d43b3834556c87ee6e8bdcbe9365f.
