### ISSUE TITLE
Excessive ACL debug information

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#558]
Since #550, we are getting excessive debug information:

```
  solid:ACL Can https://localhost:8443/profile/card#me Read https://localhost:8443/profile/card? +3m
  solid:ACL Check if ACL exists: https://localhost:8443/profile/card.acl +0ms
  solid:ACL Read access permitted to https://localhost:8443/profile/card#me +26ms
  solid:ACL Can an agent Read https://localhost:8443/profile/card? +3ms
  solid:ACL Can an agent Write https://localhost:8443/profile/card? +1ms
  solid:ACL Can an agent Append https://localhost:8443/profile/card? +0ms
  solid:ACL Can an agent Control https://localhost:8443/profile/card? +0ms
  solid:ACL Can https://localhost:8443/profile/card#me Read https://localhost:8443/profile/card? +0ms
  solid:ACL Can https://localhost:8443/profile/card#me Write https://localhost:8443/profile/card? +0ms
  solid:ACL Can https://localhost:8443/profile/card#me Append https://localhost:8443/profile/card? +0ms
  solid:ACL Can https://localhost:8443/profile/card#me Control https://localhost:8443/profile/card? +0ms
  solid:ACL Read access permitted to null +0ms
  solid:ACL Write access NOT permitted to null +1ms
  solid:ACL Append access NOT permitted to null +1ms
  solid:ACL Control access NOT permitted to null +0ms
  solid:ACL Read access permitted to https://localhost:8443/profile/card#me +0ms
  solid:ACL Write access permitted to https://localhost:8443/profile/card#me +0ms
  solid:ACL Append access permitted to https://localhost:8443/profile/card#me +0ms
  solid:ACL Control access permitted to https://localhost:8443/profile/card#me +0ms
  solid:ACL Write access denied to null +1ms
  solid:ACL Error: ACL file found but no matching policy found
  solid:ACL     at permissionSet.checkAccess.then.hasAccess (/Users/ruben/Documents/UGent/MIT/Solid/node-solid-server/lib/acl-checker.js:101:17)
  solid:ACL     at <anonymous> +0ms
  solid:ACL Append access denied to null +0ms
  solid:ACL Error: ACL file found but no matching policy found
  solid:ACL     at permissionSet.checkAccess.then.hasAccess (/Users/ruben/Documents/UGent/MIT/Solid/node-solid-server/lib/acl-checker.js:101:17)
  solid:ACL     at <anonymous> +0ms
  solid:ACL Control access denied to null +1ms
  solid:ACL Error: ACL file found but no matching policy found
  solid:ACL     at permissionSet.checkAccess.then.hasAccess (/Users/ruben/Documents/UGent/MIT/Solid/node-solid-server/lib/acl-checker.js:101:17)
  solid:ACL     at <anonymous> +0ms
  solid:ACL Error: ACL file found but no matching policy found +1ms
  solid:ACL Authentication required +0ms
  solid:ACL Error: ACL file found but no matching policy found +0ms
  solid:ACL Authentication required +0ms
  solid:ACL Error: ACL file found but no matching policy found +0ms
  solid:ACL Authentication required +0ms
```

This is because all 4 modes are checked for the current user and the public.

We should move the logging such that only the requested permissions are logged, and the others simply summarized.

**Comment by RubenVerborgh** [comment]
Fix in #566.
