### ISSUE TITLE
PoPToken.importConfirmationKey: Cannot read property 'jwk' of undefined 

### ISSUE THREAD

**Issue by timbl** [solid/node-solid-server#564]
Running nss dz_oidc branch,  Trying to edit a bug tracker  issue field logged in with OIDC to solidtest.space:

Error (while saving change to https://timbl.com/timbl/2017/Solid/HighLevelIssues/state.ttl): sparql: update failed for <https://timbl.com/timbl/2017/Solid/HighLevelIssues/state.ttl> status=500, undefined for query: INSERT DATA { <https://timbl.com/timbl/2017/Solid/HighLevelIssues/state.ttl#Iss1503090050384> <http://www.w3.org/2005/01/wf/flow#description> "This comment added 8/30 logged in with OIDC" . } 

server log i suspect matches:

  solid:server Error page because of: +50s TypeError: Cannot read property 'jwk' of undefined
    at PoPToken.importConfirmationKey (/devel/github.com/solid/node-solid-server/node_modules/@trust/oidc-rs/src/PoPToken.js:174:50)
    at PoPToken.verifyPoPSignature (/devel/github.com/solid/node-solid-server/node_modules/@trust/oidc-rs/src/PoPToken.js:149:17)
    at PoPToken.validatePoPToken (/devel/github.com/solid/node-solid-server/node_modules/@trust/oidc-rs/src/PoPToken.js:129:17)
    at validatePoPToken (/devel/github.com/solid/node-solid-server/node_modules/@trust/oidc-rs/src/AuthenticatedRequest.js:302:23)

**Comment by dmitrizagidulin** [comment]
solidtest.space is running an old version of node-solid-server. I'll update it to the latest this morning.

**Comment by dmitrizagidulin** [comment]
@timbl - I've updated solidtest.space. Let me know if this error repeats.

**Comment by dmitrizagidulin** [comment]
Works with updated server, closing.

**Comment by timbl** [comment]
In fact it seems to work but the logs still contain
  solid:server Error page because of: +589ms TypeError: Cannot read property 'jwk' of undefined
    at PoPToken.importConfirmationKey (/devel/github.com/solid/node-solid-server/node_modules/@trust/oidc-rs/src/PoPToken.js:174:50)
    at PoPToken.verifyPoPSignature (/devel/github.com/solid/node-solid-server/node_modules/@trust/oidc-rs/src/PoPToken.js:149:17)
    at PoPToken.validatePoPToken (/devel/github.com/solid/node-solid-server/node_modules/@trust/oidc-rs/src/PoPToken.js:129:17)
    at validatePoPToken (/devel/github.com/solid/node-solid-server/node_modules/@trust/oidc-rs/src/AuthenticatedRequest.js:302:23)

Reopening

**Comment by dmitrizagidulin** [comment]
Thanks, will take a look.

**Comment by dmitrizagidulin** [comment]
@timbl I added a fix in the upstream library. Do an `npm install` & restart the server, see if you get this again.

**Comment by timbl** [comment]
Still same problem in the log...
 solid:server Error page because of: +4s TypeError: Cannot read property 'jwk' of undefined

after npm i
and a pull of 928ff50

**Comment by dmitrizagidulin** [comment]
Ah, hmm, seems that just doing `npm i` doesn't pick up patch changes. 

Running `npm i @trust/oidc-rs` should do it, though.

**Comment by timbl** [comment]
Ok, I cannot now reproduce this.   Logging with OIDC and editing for example https://timbl.com/timbl/2017/Solid/HighLevelIssues/state.ttl#Iss1503090050384 seems to work
fine.
