### ISSUE TITLE
Add test for WebID with no content type

### ISSUE THREAD

**Issue by melvincarvalho** [solid/node-solid-server#623]
Occasionally a non standard WebID without a content type will try to authenticate on node-solid-server

There is some [evidence](https://gitter.im/solid/chat?at=5a563275d0514c785b137c47) that this could cause the server to crash

It would be helpful to add a test to capture this case, and it should return an HTTP 401 error code, without causing the server to go down

**Comment by melvincarvalho** [comment]
My local testing confirms that sending no content type crashes the server

```
var mimeType = contentType.replace(/;.*/, '')
                          ^

TypeError: Cannot read property 'replace' of undefined
  at verifyKey (./node-solid-server/node_modules/webid/tls/index.js:69:29)
  at ./node-solid-server/node_modules/webid/tls/index.js:38:5
  at Request._callback (./node-solid-server/node_modules/webid/lib/get.js:25:5)
  at Request.self.callback (./node-solid-server/node_modules/request/request.js:188:22)
  at emitTwo (events.js:125:13)
  at Request.emit (events.js:213:7)
  at Request.<anonymous> (./node-solid-server/node_modules/request/request.js:1171:10)
  at emitOne (events.js:115:13)
  at Request.emit (events.js:210:7)
  at IncomingMessage.<anonymous> (./node-solid-server/node_modules/request/request.js:1091:12)
```

**Comment by melvincarvalho** [comment]
Possible easy fix would be:

```JavaScript
if (!mimeType) {
    return callback(new Error('Missing content type in request'))
}
```
