### ISSUE TITLE
401 then 500 response using OIDC from a fetch request

### ISSUE THREAD

**Issue by timbl** [solid/node-solid-server#653]
See gitter for [April 25, 2018 2:16 PM](https://gitter.im/solid/node-solid-server?at=5ae071b02d0e228d7bae76d2)

It seems there is a nested error in which, in processing the OIDC authentication loop, the node server gets a fetch error that it can't validated the TLS server cert -- its own TLS server cert.

**Comment by timbl** [comment]
```
Wed, 25 Apr 2018 10:41:40 GMT solid:authentication Rejecting session for https://timbl.solidtest.space/profile/card#me from https://timbl.com
Wed, 25 Apr 2018 10:41:40 GMT solid:ACL Using ACL https://timbl.solidtest.space/settings/.acl for ./prefs.ttl
Wed, 25 Apr 2018 10:41:40 GMT solid:ACL Read access denied to (none)
Wed, 25 Apr 2018 10:41:40 GMT solid:server Error page because of: { [HTTPError: Access to https://timbl.solidtest.space/settings/prefs.ttl requires authorization]
  name: 'HTTPError',
  message: 'Access to https://timbl.solidtest.space/settings/prefs.ttl requires authorization',
  status: 401 }
Wed, 25 Apr 2018 10:41:40 GMT solid:server Access to https://timbl.solidtest.space/settings/prefs.ttl requires authorization error: undefined desc: undefined
Wed, 25 Apr 2018 10:41:40 GMT solid:server Redirecting to Select Provider: https://solidtest.space/api/auth/select-provider?returnToUrl=https://timbl.solidtest.space/settings/prefs.ttl
Wed, 25 Apr 2018 10:41:40 GMT solid:authentication Rejecting session for https://timbl.solidtest.space/profile/card#me from https://timbl.com
Wed, 25 Apr 2018 10:41:40 GMT solid:server Error page because of: { FetchError: request to https://solidtest.space/.well-known/openid-configuration failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (/root/node-solid-server/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at emitErrorNT (net.js:1283:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  name: 'FetchError',
  message: 'request to https://solidtest.space/.well-known/openid-configuration failed, reason: unable to verify the first certificate',
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
}
```

**Comment by dmitrizagidulin** [comment]
Oh, how interesting. I wonder what the ‘first certificate’ part is all about...

**Comment by dmitrizagidulin** [comment]
Ran a [test with SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=solidtest.space), and it flagged a couple of issues:

1. No [DNS CAA (Certificate Authority Authorization)](https://blog.qualys.com/ssllabs/2017/03/13/caa-mandated-by-cabrowser-forum), which I don't think is causing the SSL error, but I figured I'd mention it.
2. (Certificate) Chain Issues - Incomplete. It seems that there needs to be an intermediate SSL certificate installed as part of Gandi's issued cert. See https://community.qualys.com/thread/11685 for example discussion.

**Comment by RubenVerborgh** [comment]
@melvincarvalho @ericprud Who of you has received the certificate from Gandi?

We simply need to create a .crt that includes the full chain. From the Gandi website:

> You will want to download and install Gandi's intermediate certificate (also called the operational certificate authority) along with your Gandi SSL certificate so that visitors to your site can automatically download it and verify the trust chain. Instructions for doing this are provided along with those for installing your certificate.

**Comment by RubenVerborgh** [comment]
Found that timbl.com is also using Gandi. I'd be interested to see @timbl's config for it

Compare the output of the following:
```
openssl s_client -connect solidtest.space:443
openssl s_client -connect timbl.com:443
```

**Comment by RubenVerborgh** [comment]
Same problem with solid.community BTW:

```
openssl s_client -connect solid.community:443
```

**Comment by melvincarvalho** [comment]
@RubenVerborgh added your key to solid.community

**Comment by RubenVerborgh** [comment]
@melvincarvalho Tried to ssh into solid.community as root, but couldn't. My key is

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCw0HeR1rLUmMFkJaoG44CxxHnotzY9sXAhGlAAGUGrvD6w3Gyz0Xkzs4HHdbSi2Z2e2zr7EFQ6iSykZJ5peRGQsxbdykMFgcVaKBNOYKruoE7+/g0B4D8dWLkqA9WrnlJ58iqL8dBL848n82pz8Spwx1CP/Jbi4uTTM67WQkUDr/yVUirnv7XEQgyp7RIysmUTOJIKYN8e5HQ9V14g/5NS5JWfVFsP7PKiKsvXRoni3RMCZ6jNKZCJLZS2cD0utJcDFZ4QbnW8sseiaNoVK6dXBSCwNd6GJyuqgvTu7SB1Q7MIdcBUiCEgxZOhqM/If7tBV2zX5cEfNa9fPvSTHtBPSr9jhcSLAzY8+9OtT/YSoazNrRXtuwVDxYzG72seV3+Tqh4Gj7P4oBQaStdYZvDDgUGH3ji8Md4llrrJMkJjsfGxJN4yaHr50g6NQSixTEWMppJWkLSG08py/qJ011Dr4BAb16zIOsfkevpVnhOxZ8FpuNl/dJqsejO9TI0ynvFbzl7b3KHa2PRqfoDhw1KS4oqhSmHXLzSdas4+b4Sc5RojmGxiPhmk9xMzI9iGwCfAaGIZAT0qAOkncN8yi8qz1op1h6TriLnN4/H3Ht7RV00+y6xNpO+NDu4xd24WfJXcoFBLqLFIeJJMBYeCrC52kyZgBFuUfVzQxvH0RJ7weQ== ruben@verborgh.org
```

**Comment by RubenVerborgh** [comment]
Okay, both solidtest.space and solid.community now get an A rating.

For future reference, I fixed this as follows:
- Gandi supplies us with a _.solid.community.crt file
- This file contains a single certificate
- We need to append the contents of GandiStandardSSLCA2.pem to that file, such that this file now contains *3* certificates
