### ISSUE TITLE
Server crash on PATCH targetting a jsonld resource

### ISSUE THREAD

**Issue by PulsarFox** [solid/node-solid-server#677]
So i'm trying to send a simple Sparql query `INSERT DATA { <> <http://purl.org/dc/terms/title> "My data container" }` to a jsonld file containing the following values 
```
{
    "@context": {
        "foaf": "http://xmlns.com/foaf/0.1/",
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#"
    },
    "@subject": "#me",
    "@type": "foaf:Person",
    "foaf:firstName": "samy",
    "foaf:lastName": "vincent",
    "foaf:currentProject": "solid",
    "foaf:surname": "pulsarfox",
    "foaf:knows": "http://everyone.example.org"
}
```

I'm using fetch() api 
```
    fetch(uri + data.name, {
        method:'PATCH',
        headers:{'Content-type':'application/sparql-update'},
        body:sparqlQuery
    })
```

the server crashes with 
```
/home/savincen/Documents/ProjectNode/solid-test/node_modules/rdflib/lib/parse.js:113
      callback(null, kb);
      ^

TypeError: callback is not a function
    at N3Parser.tripleCallback [as _callback] (/home/savincen/Documents/ProjectNode/solid-test/node_modules/rdflib/lib/parse.js:113:7)
    at N3Parser._readInTopContext (/home/savincen/Documents/ProjectNode/solid-test/node_modules/n3/lib/N3Parser.js:81:19)
    at /home/savincen/Documents/ProjectNode/solid-test/node_modules/n3/lib/N3Parser.js:683:35
    at N3Lexer._tokenizeToEnd (/home/savincen/Documents/ProjectNode/solid-test/node_modules/n3/lib/N3Lexer.js:80:11)
    at Immediate._onImmediate (/home/savincen/Documents/ProjectNode/solid-test/node_modules/n3/lib/N3Lexer.js:318:38)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

```

the fetch fails with `TypeError: Failed to fetch` 

i've tried with `INSERT DATA { <> <http://purl.org/dc/terms/title> "My data container"  .}` instead of `INSERT DATA { <> <http://purl.org/dc/terms/title> "My data container"  .}` but it does the same. 

Actually even witout a query (with `body:""`) the server crashes.

**Comment by dmitrizagidulin** [comment]
Thanks, @PulsarFox! We will investigate.
