### ISSUE TITLE
Failed to lookup view "auth/login-required" in views directory

### ISSUE THREAD

**Issue by justinwb** [solid/node-solid-server#766]
When updating NSS to 4.1.1... The install goes fine, but post-install when you go to bring up a given user's url (e.g. https://justin.inrupt.net), I'm getting the following:

```
Error: Failed to lookup view "auth/login-required" in views directory "/etc/solid/views"
    at Function.render (/usr/lib/node_modules/solid-server/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/usr/lib/node_modules/solid-server/node_modules/express/lib/response.js:1008:7)
    at renderLoginRequired (/usr/lib/node_modules/solid-server/lib/handlers/error-pages.js:138:7)
    at handler (/usr/lib/node_modules/solid-server/lib/handlers/error-pages.js:32:7)
    at Layer.handle_error (/usr/lib/node_modules/solid-server/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/lib/node_modules/solid-server/node_modules/express/lib/router/index.js:315:13)
    at /usr/lib/node_modules/solid-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/node_modules/solid-server/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/solid-server/node_modules/express/lib/router/index.js:275:10)
    at /usr/lib/node_modules/solid-server/node_modules/express/lib/router/index.js:635:15
```

Copying /usr/lib/node_modules/solid-server/default-views/auth/login-required.hbs to /etc/solid/auth/views resolved the issue. Not sure if we're looking to create a symbolic link here, or copy this view upon install as the proper solve.

**Comment by dmitrizagidulin** [comment]
Makes sense, yeah. This is an ongoing issue / design decision that we need to make, described in more detail here: https://github.com/solid/node-solid-server/issues/688

**Comment by RubenVerborgh** [comment]
Let's follow up there.
