### ISSUE TITLE
Improve error handling for invalid setup for directory permissions

### ISSUE THREAD

**Issue by mohamedmansour** [solid/node-solid-server#800]
When I started the server, I got this error:
`ERROR You need root privileges to start on this port`

It doesn't make sense because I wasn't running on port 80. So debugging it more (added console statements), I found that the true error was the following:

```
{ Error: EACCES: permission denied, mkdir '/var/www/solid.mysite/config/templates'
    at Object.fs.mkdirSync (fs.js:885:18)
    at mkdirsSync (/usr/lib/node_modules/solid-server/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
    at Object.mkdirsSync (/usr/lib/node_modules/solid-server/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:37:16)
    at Object.copySync (/usr/lib/node_modules/solid-server/node_modules/fs-extra/lib/copy-sync/copy-sync.js:49:37)
    at ensureDirCopyExists (/usr/lib/node_modules/solid-server/lib/server-config.js:25:8)
    at Object.initTemplateDirs (/usr/lib/node_modules/solid-server/lib/server-config.js:108:29)
    at createApp (/usr/lib/node_modules/solid-server/lib/create-app.js:45:27)
    at Function.createServer (/usr/lib/node_modules/solid-server/lib/create-server.js:15:18)
    at bin (/usr/lib/node_modules/solid-server/bin/lib/start.js:122:17)
    at fs.readFile (/usr/lib/node_modules/solid-server/bin/lib/start.js:41:7)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/var/www/solid.mysite/config/templates' }
```

It should assist the user to fix their permissions not run it in root.

**Comment by tuxPM** [comment]
got the same error for a different path (/etc/letsencrypt/live/your.host.example.org/*.pem)

**Comment by mohamedmansour** [comment]
@tuxPM  you need to give `g+x` on the `/etc/letsencrypt/live` folder to `www-data` and g+xr on the `/etc/letsencrypt/archive` folder to www-data to make that permission work.
