### ISSUE TITLE
Solid-test crash at "# Disable rejectUnauthorized when starting the server"

### ISSUE THREAD

**Issue by josephusmv** [solid/node-solid-server#856]
I am try to run the solid server as a developer without formal CA. So I followed the Readme and tried to replace the std solid from "solid.cmd" to solid-test

  "%~dp0\node.exe"  "%~dp0\node_modules\solid-server\bin\solid" %*
  "%~dp0\node.exe"  "%~dp0\node_modules\solid-server\bin\solid-test" %*

But when I try to run solid,(I believe it should be running this solid.cmd) it will crash with below outputs:
$ solid
C:\Users\Jomu_\AppData\Roaming\npm\node_modules\solid-server\bin\solid-test:6
# Disable rejectUnauthorized when starting the server
^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

I am using the master branch, please suggest me what should I check, thanks.

**Comment by dmitrizagidulin** [comment]
The ‘invalid token’ part suggests that you’re running an earlier version of Node. solid-server requires Node 8 and above.

**Comment by dmitrizagidulin** [comment]
Oh wait. No, it’s the fact that ‘solid-test’ is a bash script, not a node script. So you dont want to run it with node.exe.

Btw, solid-server is not supported or tested on Windows. You’re likely going to run into errors with native crypto, on windows.

**Comment by kjetilk** [comment]
Was your question answered, @josephusmv ?

**Comment by josephusmv** [comment]
Hi, @dmitrizagidulin, sorry for the late reply.

1. My node version is v8.12.0
Jomu_@LAPTOP-PTBKQDUP C:\Users\Jomu_\go\src\github.com\josephusmv
$ node --version
v8.12.0

2. I am using solid.cmd, which is a batch command. And thanks for the notification, the solid-test is a bash script. Silly me, thanks for noticing~ I will try to convert it to windows. Let me know this is an mission impossible or there already has one windows version existed.

@kjetilk Yes, I think so.
I also think you could close the issue IF you know there is a windows version of solid-test command batch, or you think this is unnecessary. I am totally new to solid, and this is a brilliant new thing. Sorry for the silly question.

**Comment by kjetilk** [comment]
@josephusmv I think we should support developers on Windows. I'm not aware of any corresponding script that could help, but that doesn't mean it doesn't exist, I just don't know anyone who is using Windows for Solid development. 

A PR for a batch script that plays the role of `solid-test` will be most welcome!

**Comment by josephusmv** [comment]
Sorry for the late replay, too busy on works...And Thanks for your kindness, since I realized that cygwin definitely be a better choice. 
A direct interpret would be quite easy:
```bash
echo off
set COMMAND=%1
set ADD_FLAGS
shift

REM Disable rejectUnauthorized when starting the server
IF "%COMMAND%" == "start" (
  SET ADD_FLAGS=--no-reject-unauthorized
  SET NODE_TLS_REJECT_UNAUTHORIZED=0
)

REM SET CALL_CLI_STR=require('./lib/cli').startCli('%COMMAND%','%ADD_FLAGS%','%*')
SET CALL_CLI_STR=require('./lib/cli').startCli()
echo CALL_CLI_STR: %CALL_CLI_STR%
node -p  %CALL_CLI_STR%
```

But I am not quite understand the internal logics, the calling process failed on parameter checking:
```
 TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at basename (path.js:820:5)
    at Command.parse (C:\Users\Jomu_\AppData\Roaming\npm\node_modules\solid-server\node_modules\commander\index.js:465:30)
    at Object.module.exports.startCli (C:\Users\Jomu_\AppData\Roaming\npm\node_modules\solid-server\bin\lib\cli.js:14:11)
    at [eval]:1:22
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:653:30)
    at evalScript (bootstrap_node.js:479:27)
```

I believe this should be caused by illegal parameter to the cli.js.startCli(server) function. I may need further digest to the meaning of the server parameter...

B.T.W., just F.Y.I., The export function of startCli cannot be eval'ed using the current style:
```javascript
module.exports = function  startCli(server) {
}
```
But it can be eval'ed using below way:
```javascript
module.exports.startCli = function (server) {
}
```

**Comment by kjetilk** [comment]
Mmmm, I don't understand much of this, @dmitrizagidulin , can you help?
