### ISSUE TITLE
Does not work on Node <= 8

### ISSUE THREAD

**Issue by fnoorden-vs** [solid/node-solid-server#972]
Centos 7
solid-server@4.4.0
node v6.14.3

# solid init 
/usr/lib/node_modules/solid-server/bin/lib/start.js:37
  start.action(async (options) => {
                     ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/solid-server/bin/lib/cli.js:3:19)

Help will be appreciated!

**Comment by RubenVerborgh** [comment]
Your Node version is too old; at least 8 is required.

**Comment by fnoorden-vs** [comment]
Thanks Ruben for the fast solution.
